### ISSUE TITLE
Update httpoison dep

### ISSUE THREAD

**Issue by davedoesdev** [cwc/eventsource_ex#3]
When I compile `eventsource_ex`, I get the following warnings:

```
===> Compiling hackney
src/hackney_pool.erl:213: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1

src/hackney_multipart.erl:271: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
```

I think the first one at least is definitely a good reason to upgrade?

**Comment by cwc** [comment]
Sure, I've got no problem updating deps since I can lock existing upstream projects to a given commit hash.

Thanks for putting in some time on this btw. If you squash all the warnings and get the deps updated for me, I'll push a release to Hex.

**Comment by davedoesdev** [comment]
Sure, I can do that. Might be a couple of days till I get round to it...

**Comment by cwc** [comment]
Yeah no worries. I whipped this up for a work project but made it a separate module because I figured it'd be handy in other apps/for other people, hence the lack of updates. It's working in prod so good enough for me. 😁

**Comment by davedoesdev** [comment]
@cwc I just grabbed a moment and did a PR.

**Comment by davedoesdev** [comment]
Btw thanks for this module, I'm using it [https://github.com/davedoesdev/centro/tree/initial-wip#elixir](here).

**Comment by cwc** [comment]
Awesome! Very cool to see that it's useful for someone else. 🎉 I'll try to push a release soon.

**Comment by davedoesdev** [comment]
Thanks

**Comment by davedoesdev** [comment]
Hey @cwc thanks again for this library. Is there any chance of publishing it to hex?

**Comment by cwc** [comment]
v0.0.1 has been published to Hex. :)

**Comment by davedoesdev** [comment]
@cwc thanks

**Comment by davedoesdev** [comment]
By the way, I get this warning when compiling:

```
==> eventsource_ex
warning: the dependency :eventsource_ex requires Elixir "~> 1.3.4" but you are running on v1.4.5
Compiling 2 files (.ex)
Generated eventsource_ex app
```

Do you know why I get that warning but I don't when I compile httpoison which has `elixir: "~> 1.2"` in its `mix.exs` file?

**Comment by davedoesdev** [comment]
Is `~>` saying only the final number in the version can change?

**Comment by davedoesdev** [comment]
https://hexdocs.pm/elixir/Version.html
@cwc was your intent only to support Elixir 1.3?

**Comment by cwc** [comment]
I intended to declare the required version as the lowest on which I've confirmed that the library now works, which is 1.3.x due to the use of its DateTime module. 1.4 and beyond will likely continue to work fine as I doubt they'll make breaking changes.

I'll set the required version to `~> 1.3` for the next version I push, which shouldn't show a warning for any 1.x after 1.3.

**Comment by davedoesdev** [comment]
@cwc thanks!

**Comment by davedoesdev** [comment]
Hi @cwc is it okay to push another version with that change please?

**Comment by cwc** [comment]
Sure, I can try to do that soon. Before I do, have you come across any other changes you'd like to see? I haven't needed to do any development on the lib myself, as it's holding up very well in production as-is.

**Comment by davedoesdev** [comment]
Nope, seems very solid - nice work

**Comment by cwc** [comment]
v0.0.2 has been published. I've verified that there are no warnings for Elixir 1.5.

**Comment by davedoesdev** [comment]
Confirmed - thanks again
