### ISSUE TITLE
Next Major version release?

### ISSUE THREAD

**Issue by AtibaBryan** [cwc/eventsource_ex#9]
Hi @cwc I'm getting farther along in my project and I'm wondering if you have plans to release the next version as I'd like to point to the upstream project instead of my fork. 
I'm very well aware that:
1. I have no idea how busy you are.
2. I have no idea how much work this for you on your end.

I am willing to help in any way that's not a security risk and realize you are an unpaid maintainer so I'm not trying to be a spoiled open source brat.
Thanks for making the only client side http streaming library I know of for elixir and cheers. 🍻

**Comment by cwc** [comment]
Hey thanks man, no worries, it's a totally reasonable question and I'm glad that other people are finding the project useful!

I do want to push up a new version to Hex, but I'd like to test the new changes in our stack at work first, just to see if there are some tweaks that should be made. I should be able to find time for that this week (fingers crossed 😅 ).

**Comment by DwordPtr** [comment]
Totally understand. 

Let me know if you could use some help on those tweaks.

Have a good weekend. 🍻

**Comment by davedoesdev** [comment]
Be nice to have a new version on Hex. Happy to help if I can.

**Comment by davedoesdev** [comment]
Any update?

**Comment by adamwight** [comment]
:+1: I'm also interested in a new version, to get the newer HTTPoison dependency.  Nice work on this project, thank you!  Here's my [downstream usage](https://gitlab.com/adamwight/wiki_elixir/) in case of curiosity.

**Comment by adamwight** [comment]
I ran into a blocker when trying to use the 0.0.2 release: the older version of Hackney included from this is incompatible with Erlang/OTP 22.1 when using the https protocol.  See benoitc/hackney#591.

**Comment by davedoesdev** [comment]
@adamwight using the `{:eventsource_ex, github: "cwc/eventsource_ex"}` in your dependencies should work.
Not ideal but :man_shrugging:

**Comment by cwc** [comment]
I've pushed version 1.0.0 to Hex. Better late than never right?
